#app/services/media_server.py
import json
import os
import urllib.parse
import streamlit as st

CONFIG_FILE = "server_config.json"

def get_base_url():
    """Reads the dynamic Cloudflare URL generated by the bash script."""
    if os.path.exists(CONFIG_FILE):
        try:
            with open(CONFIG_FILE, 'r') as f:
                data = json.load(f)
                return data.get("MUSIC_SERVER_URL", "")
        except:
            return ""
    return ""

def get_audio_url(rel_path):
    base = get_base_url()
    if not base:
        return None
    # Ensure URL encoding for Hebrew filenames
    encoded_path = urllib.parse.quote(rel_path)
    return f"{base}/{encoded_path}"
